### ISSUE TITLE
Strategia pozyskania danych

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/AITech-flats#1]
Musimy zresearchować i zdecydować w jaki sposób pozyskamy dane.
Do zrealizowania projektu potrzebujemy zdjęcia różnych wnętrz mieszkań oznaczonych ich stylem.

**Comment by Adelionek** [comment]
Najlepiej aby zdjęcia były realne, zrobione przez normalnych/amatorskich ludzi. Jako mockup możemy część danych pozyskać z stronek z zdjęciami wystroju wnętrz.

Przykłady:
- https://www.houzz.com/photos/home-design-ideas-phbr0-bp~
- https://architizer.com/image-search/popular-images/type=Private%20House/style=Futuristic
- https://www.archdaily.com/search/images/space/living-room/categories/apartment-interiors

**Comment by Adelionek** [comment]
Zrobiłem mały research regulaminów popularnych stron z nieruchomościami, z których potencjalnie można zescrapować dane. OLX i Otodom z bomby odpadają.

Wychodzi na to, że można zesrapować **[Lento.pl](http://lento.pl/)**

### [Domiporta](domiporta.pl)
- Wykorzystanie jakichkolwiek materiałów zgromadzonych na Serwisie (w całości lub części) przez Użytkownika bez uprzedniej zgody Właściciela i udostępnianie ich osobom trzecim lub innym serwisom ogłoszeniowym (w tym własnym) jest niedozwolone. Powyższe czynności Użytkownika każdorazowo wymagają udzielenia oddzielnej pisemnej zgody przez Właściciela
###  [Gethome](gethome.pl)
- Z chwilą wyboru przez Wydawcę danego Ogłoszenia Partner, który je zgłosił udziela Wydawcy nieodpłatnej i niewyłącznej licencji, bez prawa do udzielania sublicencji na korzystanie przez Wydawcę bez ograniczeń terytorialnych z praw autorskich do Ogłoszenia, w tym zdjęć i innych utworów do niego dodanych, a także praw zależnych do nich na następujących polach eksploatacji:
   - w zakresie rozpowszechniania tych utworów poprzez ich publiczne udostępnienie w taki sposób, aby każdy mógł mieć do nich dostęp w miejscu i czasie przez siebie wybranym, w szczególności przez Internet,
   - w zakresie utrwalania i zwielokrotniania utworów, w szczególności poprzez ich wprowadzenie do pamięci komputera lub innego urządzenia końcowego.
### [Gratka.pl](Gratka.pl)
- Wszelkie elementy graficzne, rozwiązania techniczne i inne elementy strony WWW Serwisu, w szczególności kod HTML i XHTML, arkusze CSS, skrypty JavaScript i linki multimedialne, do których prawo nie przysługuje Użytkownikom, podlegają ochronie prawnej pod kątem praw autorskich przysługujących Spółce.
- Spółka nie ponosi żadnej odpowiedzialności względem Użytkowników za sytuacje związane z naruszeniem ich praw autorskich i innych związanych z ogłoszeniami, ich przedmiotem lub treścią, przez podmioty trzecie. W szczególności Spółka nie ponosi odpowiedzialności za nieautoryzowane umieszczanie ogłoszeń, ich części lub elementów przez podmioty trzecie na innych serwisach internetowych lub w innych mediach, za wykorzystywanie ogłoszeń, ich części lub elementów przez podmioty trzecie w celach komercyjnych, a także za podszywanie się przez podmioty trzecie pod Użytkowników.
### [Lento.pl](http://lento.pl/)
- Użytkownik, publikując Ogłoszenie i zawarte w nim treści w tym zdjęcia i numer telefonu **podaje je dobrowolnie do wiadomości publicznej i zgadza się na ujawnienie ich innym Użytkownikom** w szczególności osobom korzystającym z sieci Internet. Ogłoszenia również mogą być indeksowane przez wyszukiwarki, czego Użytkownik ma świadomość i na co Użytkownik wyraża zgodę.
### [okolica.pl](http://okolica.pl/)
- Zawartość  Serwisu stanowi własność Usługodawcy i jest prawnie chroniona.
### [Sprzedajemy.pl](http://sprzedajemy.pl/)
- Wszelkie rozwiązania techniczne, elementy graficzne i inne elementy strony WWW Serwisu i aplikacji mobilnych, w szczególności kod HTML i XHTML, arkusze CSS, skrypty JavaScript podlegają ochronie prawnej w zakresie praw autorskich przysługujących Spółce.
### [szybko.pl](http://szybko.pl/)
- Użytkownik uznaje, że całość praw autorskich, wszystkie znaki towarowe, konta Użytkowników oraz pozostałe prawa własności intelektualnej związane z usługami serwisu [SZYBKO.PL](http://szybko.pl/) należą do [Szybko.pl](http://szybko.pl/) Sp. z o.o.

**Comment by Adelionek** [comment]
Opcja trzecia - skorzystanie z danych użytych innych pracach naukowych i projektach.

- https://www.kaggle.com/robinreni/house-rooms-image-dataset
-

**Comment by Adelionek** [comment]
Po spotkaniu 15.11.2022 ustaliliśmy, że jako mockup danych możemy wykorzystać dane zescrapowane z witryn internetowych w celach naukowych [link do ustawy](https://sip.lex.pl/akty-prawne/dzu-dziennik-ustaw/prawo-autorskie-i-prawa-pokrewne-16795787/art-27).

Strategia:
- Zebranie danych z olx/otodom
   - Te dane powinny być w strukturze źródło -> województwo -> miasto -> zdjęcia
- Zebranie danych z houzz.com
   - Te dane powinny być w strukturze źródło -> zdjęcia
- Wstępne wyczyszczenie danych 
- Wrzucenie danych na bloba (Azure) lub inny cloudowy storage
