### ISSUE TITLE
Rozpoznanie w dostępnych platformach / maszynach obliczeniowych

### ISSUE THREAD

**Issue by MatOgr** [emkarcinos/AITech-flats#18]
W pierwszej kolejności do rozważenia:
- Azure (uczelnia)
- maszyny wydziałowe
- centrum SI (?)
- opłacenie wybranej platformy ze środków grantowych
- Colab jako 'ostateczna' alternatywa

**Comment by jolovesh** [comment]
Tu są informacje i zasady korzystania z maszyn uczelnianych:
https://laboratoria.wmi.amu.edu.pl/uslugi/zasoby-dla-projektow/maszyna-gpu/
Andre na moodlu podrzucił też to:
https://wandb.ai/site

**Comment by Adelionek** [comment]
Zrobiłem kilka testów używając Azure Machine Learning Studio, jest to dość ciekawe i użyteczne narzędzie.

Z czego możemy skorzystać?
- **Wykonywanie eksperymentów lokalnie i wrzucanie modeli/metryk do Azure**. Można używać 'Azurowych' metryk lub zintegrować to z MLflow i używać AzureMlStudio jako 'upstream server'.

  ![Image](https://user-images.githubusercontent.com/31924910/211191180-a76c2266-d5d7-455c-8d65-39028bb0398e.png)

- Tool do labelowania - Po stworzeniu projektu do Data Labelingu i dodaniu datasetu można w łatwy sposób etykietować zdjęcia. Możliwość dodania kilku labelerów. Możliwość konfiguracji np. wymagane potwierdzenie labelu przez minimum 2 członków.

  ![Image](https://user-images.githubusercontent.com/31924910/211190846-b44e2551-b803-4ae5-9c08-a997e464844b.png)

  ![Image](https://user-images.githubusercontent.com/31924910/211190849-6ce57b31-2cfc-4fef-8833-2fc24ee0b509.png)

- Maszyny GPU/CPU
  ![Image](https://user-images.githubusercontent.com/31924910/211190914-409e0d85-77ce-4dea-bb0e-cf38a9892fd8.png)

- Wykonywanie eksperymentów w notebooku na AzureMlStudio używając CPU/GPU od Azure.
- Pipeline do tworzenia całego flow od danych, przed trenowanie modelu do inferencji (nie testowałem tego)

**Comment by Adelionek** [comment]
Jedyny 'problem' przy stosowaniu AzureMlStudio, to że musielibyśmy chyba skorzystać z licencji studenckiej. Ja mam subskrypcję z limitem 150usd miesięcznie ale nie mogę dodać tam żadnego użytkownika do kolaboracji.

**Comment by emkarcinos** [comment]
Zamykam - wybraliśmy Azure ML Studio
