### ISSUE TITLE
Zlecenie poetykietowania zdjęć

### ISSUE THREAD

**Issue by ulaniuk** [emkarcinos/AITech-flats#19]
Kontynuacja: #21 

Można to potencjalnie zrobić za pośrednictwem Amazon SageMaker'a lub bezpośrednio z firmą zajmującą się etykietowaniem/grupą studenciaków.

W przypadku firmy dajemy im wytyczne, oni szkolą parę osób do etykietowania i pracują. Mamy większą kontrolę i jakość niż w przypadku Mechanic Turka. Ze względu na nasz ograniczony budżet kontakt bezpośredni raczej odpada.

Przedstawiciel z którym rozmawiałem w Tel Awiwie mówił że nie ma problemu żeby po kontakcie mailowym ustalić podobne zasady przez Amazon SageMaker'a. Problem w tym że Amazon pradopodobnie nie wystawi nam faktury (trzeba doczytać/skontaktować się).

W przypadku studentów nie dostaniemy od nich faktury na study@research ale może uda się to ogarnąć w ramach uczelni jako współpraca między uczelniami. Architekturę wnętrz w Poznaniu porawdzą na Politechnice Poznańskiej i Uniwersytecie Artystycznym.

Dane przedstawiciela z Tel Awiwu:
iMerit: Gabriele Tabucco
gabriele@imerit.net
iMerit.net

**Comment by MatOgr** [comment]
Na chwilę obecną jesteśmy wstępnie dogadani z jedną osobą, która podejmie się labelowania zdjęć

**Comment by Adelionek** [comment]
Przenoszę zadanie do review,  tutaj już nic się nie zmieni. Tak jak napisał Mateusz - jesteśmy dogadani już z firmą na labelowanie.

**Comment by MatOgr** [comment]
Zadanie zrealizowane, przenoszę do zamkniętych
