### ISSUE TITLE
Stworzenie wytycznych do etykietowania danych

### ISSUE THREAD

**Issue by ulaniuk** [emkarcinos/AITech-flats#21]
Kontynuacja: #16 

Wytyczne, które zostaną wykorzystane przez osoby którym outsourcujemy etykietowanie.

**Comment by Adelionek** [comment]
Wstępnie w następny weekend (14.01.2023-16.01.2023) zacznie się labelowanie. Do tego czasu to zadanie powinno być skończone.

**Comment by ulaniuk** [comment]
Częściowo opisałem czym się charakteryzują style. Na następnym spotkaniu przegadamy na jakie się decydujemy i mogę przejąć to zadanie.

**Comment by MatOgr** [comment]
Zaproponowane przez eskpertkę:

1. nowoczesny
2. skandynawski
3. industrialny/loftowy
4. vintage
5. eklektyczny
6. rustykalny
7. klasyczny
8. glamour
9. minimalistyczny
10. prowansalski
11. boho

Pytanie czy chcemy dodawać także style lokalne (zakopiański, nowojorski, hamptons itd.)

**Comment by MatOgr** [comment]
Wydaje mi się, że wszystko zostało już ustalone i prace ruszyły. Przerzucam do review, jeśli wszystko się potwierdzi, można przerzucić do zrealizowanych

**Comment by Adelionek** [comment]
Labelowanie już trwa, wymagania zostały ustalone. Zamykam.
