### ISSUE TITLE
Przejrzeć możliwości trenowania modelu na GPU

### ISSUE THREAD

**Issue by Adelionek** [emkarcinos/AITech-flats#22]
Trzeba sprawdzić jakie mamy możliwości do trenowania modelu na GPU w chmurze. Na pewno do wyboru mamy Azure, uczelniane maszyny, Collaba i może jakieś inne darmowe maszyny??

Zadanie polega na sprawdzeniu każdej możliwości i opisaniu rezultatów.

**Comment by MatOgr** [comment]
Jest już #18, pytanie który zostawiamy

**Comment by Adelionek** [comment]
Duplicate, rozwiązane w #18 - zamykam.
