### ISSUE TITLE
Zebranie danych wg ustalonej strategii

### ISSUE THREAD

**Issue by Adelionek** [emkarcinos/AITech-flats#23]
Zadanie polega na zebraniu danych wg ustalonej strategii i upload danych na jakiś serwer skąd zespół będzie mógł je pobrać.
Dane po pobraniu należy ręcznie przejrzeć i usunąć nieprawidłowe zdjęcia (z watermarkami, niepoprawnie pobrane, słabej jakości itp.)

**Comment by Adelionek** [comment]
Dane dostępne pod linkiem: 

https://drive.google.com/drive/folders/1l2NKuOhseOVmZqnD3Ej_k6Y9mNn_yzWB?usp=share_link

Łącznie jest około 20k zdjęć.

**Comment by emkarcinos** [comment]
Super robota.

Przejrzałem te dane i dane z OLX będą wymagały sporo pracy z labelowaniem i wyrzuceniem śmieci.
Dane z Houzz mnie trochę niepokoją, bo wiele z tych styli dość mocno się ze sobą miesza i mi niektóre nie pasują do kategorii w których są. Myślę, że na razie do uzyskania pierwszych rezultatów jest to enough, ale pomyślałbym czy jeszcze nie poklasyfikować ich na nowo.
