### ISSUE TITLE
Dodanie nowych metryk do ewaluacji

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/AITech-flats#33]
We wstępnej wersji frameworku metryki które śledzimy to proste precision, accuracy, recall i f-score. Dodatkowo wyświetlamy źle sklasyfikowane zdjęcia. 

@adelionek wspominał coś o ROC i Confusion matrix, warto to dodać

**Comment by Adelionek** [comment]
Link to pull request: [link](https://github.com/emkarcinos/AITech-flats/pull/48)
