### ISSUE TITLE
Przygotowanie szablonu postera na sesję 16.01

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/AITech-flats#34]
Dwukolumnowy układ
- opis problemu 
- opisać dataset
- metoda pozyskania
- wykres rozkładu klas
- diagram działania
- opis modelu
- metryki per model

**Comment by emkarcinos** [comment]
![IMG_20230110_145510969.jpg](https://user-images.githubusercontent.com/11946540/211569771-0c8475a6-385c-4674-8e55-4d54764b978d.jpg)

**Comment by ulaniuk** [comment]
Średnie mi się zdawały te szablony na canvie to zrobiłem od zera.
https://www.canva.com/design/DAFX3Iz_e_M/bFGaW8lZN3tUFgkE5UHlCA/edit?utm_content=DAFX3Iz_e_M&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

Wzorowałem się na tym:
http://rcv.kaist.ac.kr/index.php?mid=rcv_researcharea&page=2&document_srl=7145&listStyle=viewer



![Image](https://user-images.githubusercontent.com/59340529/212771123-681a594a-2dcc-4f8d-a9df-e1c012532fd3.png)

**Comment by ulaniuk** [comment]
A i pierw próbowałem zrobić w powerpoincie, ale na wersji z Office365 biednie to wyszło:
https://uam-my.sharepoint.com/:p:/g/personal/micula_st_amu_edu_pl/EQ7wbLFk4H1PvBBHSg09a74BxkLryLU11CKk_IoMA25f-g?e=bY8X9D
