### ISSUE TITLE
Przetrenować testowe modele do transferu stylu

### ISSUE THREAD

**Issue by MatOgr** [emkarcinos/AITech-flats#38]
Rozpatrujemy dwa rodzaje - GANy oraz segmentatory. Oba docelowo będą potrzebne, choć warto zrobić bardziej doglębne rozpoznanie. 

GANy:
1. CycleGAN (unsupervised)
2. pix2pix (supervised, label→image)

Segmentatory – potrzebne rozpoznanie #39

**Comment by MatOgr** [comment]
Trening przeprowadzono na `ArtDecor` ze zbioru `Houzz` – wyniki są 'jako takie', ale ogólnie widać, że działa i mniej więcej wie czego oczekujemy...

Kiedy znowu będziemy mieli dostęp do GPU przeprowadzimy trening na pozostałych stylach

**Comment by MatOgr** [comment]
Treningi poszły. Zamykam

**Comment by emkarcinos** [comment]
A gdzie kod?
