### ISSUE TITLE
Stworzyć prototyp klienta

### ISSUE THREAD

**Issue by MatOgr** [emkarcinos/AITech-flats#40]
Na obecne potrzeby wystarczyłby interfejs ładujący plik i przesyłający dane do inferencji na backend.
Wystarczy Streamlit

**Comment by MatOgr** [comment]
Prototyp działa, od wczytania zdjęć po inferencję i wyświetlenie wyniku. Na razie lokalnie, w dalszych planach stworzenie apki docelowej

**Comment by emkarcinos** [comment]
Spoko, a gdzie kod?
