### ISSUE TITLE
Integracja obecnego kodu z MLFlow / Azure

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/AITech-flats#44]
Obecna wersja kodu zapisuje model do pliku, pokazuje wykresy z wynikami i wybrane zdjęcia które zostały źle sklasyfikowane. Całość działa w porządku, natomiast chcemy to spiąć tak, żeby było wszystko udostępnione na wybranej platformie - MLFlow.

Każdy model powinien być zarchiwizowany wraz z:
- metrykami, które obecnie są wyliczane
- wykresem przedstawiającym źle sklasyfikowane obrazy
- heatmapy - po #43
- diagramu z metrykami - opcjonalne, być może będzie można to przeglądać na platformie bez konieczności wrzucania ręcznie wygenerowanych wykresów

**Comment by Adelionek** [comment]
To zadanie zostało zamknięte w tym PR: #67

**Comment by Adelionek** [comment]
Metryki wraz z modelem są archiwizowane po każdym eksperymencie. Heatmapa zostanie dodana w innym tasku.

![Image](https://user-images.githubusercontent.com/31924910/226102140-2bcb627a-44ba-4ba9-9fd5-97f15d4e5c58.png)
