### ISSUE TITLE
Wykupienie kursu z OpenCV

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/AITech-flats#5]
Wykorzystując środki z grantu chcemy wykupić kurs na OpenCV.

**Comment by Adelionek** [comment]
Skontaktowałem się z OpenCV w sprawie kursu: DEEP LEARNING WITH TENSORFLOW & KERAS. Otrzymałem już fakturę do opłaty. Jestem w trakcie rozmowy z Panią Justyną a także sopk@amu.edu.pl

**Comment by Adelionek** [comment]
Kurs został zakupiony. Podpisałem dokumenty, przeszło to przez Panią Justynę i trafiło do sopk@amu.edu.pl. Teraz czekamy aż uczelnia opłaci fakturę.

**Comment by Adelionek** [comment]
Faktura opłacona, mamy od jakiegoś czasu dostęp do kursu. @ulaniuk dostał dane do logowania i robi postępy z kursem.

**Comment by Adelionek** [comment]
**WAŻNE !!!** - Do rozliczenia S@R będzie potrzebny certyfikat z kursu.
