### ISSUE TITLE
[Klasyfikacja] Przygotować abstrakt prac na konferencję 

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/AITech-flats#58]
Chcemy zgłosić nasze postery na konferencję w Kanadzie i na PP-RAI, a jako wymóg jest abstrakt opisujący projekty.

**Comment by Adelionek** [comment]
Wspólnie przygotowane abstrakty zostały już wysłane na konferencje CAIAC i  PP-RAI. 

Załączam tu abstracty, które finalnie poszły w zgłoszeniu.
[PPRAI_Abstract.pdf](https://github.com/emkarcinos/AITech-flats/files/11008285/PPRAI_Abstract.pdf)
[CAIAC_Abstract.pdf](https://github.com/emkarcinos/AITech-flats/files/11008286/CAIAC_Abstract.pdf)
