### ISSUE TITLE
Mockupowy dataset

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/AITech-flats#6]
Możliwe do realizacji po określeniu konkretnych styłów rozważanych w projekcie

**Comment by emkarcinos** [comment]
A to w sumie w dużej mierze zostało już zrobione w https://github.com/emkarcinos/AITech-flats/issues/25

**Comment by Adelionek** [comment]
Przenoszę do review jako, że nie ma tutaj żadnego update. Mamy mockowy dataset i mamy kod do obróbki/treningu a nim.
