### ISSUE TITLE
Wysłać zgłoszenia na konferencje

### ISSUE THREAD

**Issue by emkarcinos** [emkarcinos/AITech-flats#60]

**Comment by Adelionek** [comment]
To jest URGENT!! Do jutra muszę wysłać te wnioski w celu wstępnego rozliczenia programu S@R - @emkarcinos @ulaniuk 


![Image](https://user-images.githubusercontent.com/31924910/216806903-eb8d278f-ed70-402f-8077-15543fb87100.png)

**Comment by ulaniuk** [comment]
Możemy wysłać ten z pbru. Z tego co kojarze na tym kanadyjskim sympozjum można im przesłać wstępna wersję i potem edytować ale jeszcze się upewnię

**Comment by ulaniuk** [comment]
Nie mogę znaleźć tej informacji to może mi się coś ubzduralo. Trzeba przygotować to zgodnie z szablonem, teraz wysyłamy na konfe w Łodzi czy w Kanadzie? @Adelionek @emkarcinos
